### ISSUE TITLE
Dom7 produced GET request with selected method "POST" when request url ends with slash

### ISSUE THREAD

**Issue by nedobylskiy** [nolimits4web/Dom7#1]
For example:

Basic POST request 

$$.ajax({method:"POST", data: {}, url:'/search/search/0/123'})
![image](https://cloud.githubusercontent.com/assets/4935677/25808046/8a861aec-3411-11e7-9c8f-47984bffc31f.png)

creates POST request. But if we add slash to end of url we have GET request:

$$.ajax({method:"POST", data: {}, url:'/search/search/0/123/'})

![image](https://cloud.githubusercontent.com/assets/4935677/25808056/9541d78c-3411-11e7-8a39-b55cdbd090e4.png)

Framework 7 version: v1.6.0

**Comment by nolimits4web** [comment]
Closing as not relevant anymore
