### ISSUE TITLE
Live/Delegate Event Handler not working with focus/blur

### ISSUE THREAD

**Issue by qkdreyer** [nolimits4web/Dom7#10]
https://jsfiddle.net/nu1zentc/11/

Console output :
```
focus input FocusEvent 
click input MouseEvent
delegate click input MouseEvent
blur input FocusEvent
```

Expected Console output :
```
focus input FocusEvent 
> delegate focus input FocusEvent
click input MouseEvent
delegate click input MouseEvent
blur input FocusEvent
> delegate blur input FocusEvent
```

**Comment by nolimits4web** [comment]
This is due to the nature of these events (focus/blur) and how they bubble. Use capture to assign live events for focus/blur
```js
$(document).on('focus', 'input', handler, true)

**Comment by qkdreyer** [comment]
Would it be possible to auto capture such events, so the Live/Delegate API would match with jQuery's ?

**Comment by qkdreyer** [comment]
Thanks for the fast reply answer by the way !
