### ISSUE TITLE
problem with `dom7.module.js` when use Dom7 in production environment

### ISSUE THREAD

**Issue by achmadk** [nolimits4web/Dom7#2]
Excuse me, Mr. @nolimits4web. I have an app project with Framework7. Before Framework7 version 1.6.0 has released, I use `UglifyJsPlugin` from `webpack` to minify javascript codes. After I update Framework7 version to 1.6.4 and install Dom7, I got `unexpected token` error in `dom7.module.js` file. I have changed `UglifyJsPlugin` to `babel-preset-env` and `babel-preset-babili` combination still give same result.

It seems that `dom7.module.js` file is written with ES2015 code which is not supported in UglifyJS. My temporary solution is change module attribute inside `package.json` from `dist/dom7.module.js` to `dist/dom7.js`.

**Comment by nolimits4web** [comment]
You should use Babel or Buble to transpile ES2015 code into usual JS before doing uglify. Otherwise yes, use just dom7.js file
