### ISSUE TITLE
JS error on IE11 tablet for trigger function

### ISSUE THREAD

**Issue by vitaliel** [nolimits4web/Dom7#41]
Error:  TypeError · Object doesn't support this action

User agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; rv:11.0) like Gecko

Error:
<img width="710" alt="dom7-error" src="https://user-images.githubusercontent.com/995/105056017-614fdb00-5a7c-11eb-8042-af4eac5a044c.png">

**Comment by nolimits4web** [comment]
IE11 is not supported by Dom7 and Swiper
