### ISSUE TITLE
Dom7 event: this not refer to the current element

### ISSUE THREAD

**Issue by erwinyusrizal** [nolimits4web/Dom7#51]
Hi @nolimits4web I have 4 inputs with class `.input-otp` and an event listen to the keyboard keyup. But the `this` and `$(this)` seems not refer to the current element

this ==> undefined
$(this) ==> Dom72

```
$on('pageMounted', () => {
	$('input.input-otp').on('keyup', (e) => {
		console.log(this, $(this))
	}, true)
})
```

any idea?

thank you

**Comment by nolimits4web** [comment]
This is how arrow functions work https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
