### ISSUE TITLE
Doesn't work in IE 11

### ISSUE THREAD

**Issue by JCKodel** [nolimits4web/Dom7#6]
While running this app (https://assistente-pessoal-diva.azurewebsites.net) on Internet Explorer 11, Dom7 is caught in IE madness with a syntax error:

![image](https://user-images.githubusercontent.com/379339/34170452-0ac4ca52-e4d2-11e7-8488-38dea6e30ab2.png)

![image](https://user-images.githubusercontent.com/379339/34170509-45af8f08-e4d2-11e7-8f59-33ac4cdacfcd.png)

```.navbar-inner:not(.cached)``` is not a valid syntax for ```querySelectorAll```, so IE stupidly throws a Syntax error =\

**Comment by nolimits4web** [comment]
Error probably somewhere else, `.navbar-inner:not(.cached)` is a valid selector

**Comment by Riccardo-Andreatta** [comment]
The syntax error may depend on the Webpack modules fixed in this PR https://github.com/nolimits4web/dom7/pull/26 but they seem not willing to merge it as it is there since June
